os:
  - Visual Studio 2015

platform: x64
  - x64

branches:
  only:
    - master
   
install:
  - git submodule update --init --recursive
  - cinst cmake
  - set PATH=%PATH%;C:\Program Files\CMake\bin
  - set PATH=%PATH%;%QTDIR%\bin;%QTDIR%\lib\cmake
  - set Qt5Core_DIR=%QTDIR%

build:
  verbosity: detailed

configuration:
  - Debug
  
environment:
  matrix:
    - env_arch: "x64"
      QTDIR: C:\Qt\5.8\msvc2015_64
    - env_arch: "x86"
      QTDIR: C:\Qt\5.8\msvc2015
  
build_script:
  - mkdir build
  - cd build
  - if [%env_arch%]==[x64] (
      cmake .. -A x64 )
  - if [%env_arch%]==[x86] (
      cmake .. )
  - cmake --build .
  - cd ..
